version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    versioning-strategy: increase
    schedule:
      interval: "weekly"
    groups:
      rust:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    groups:
      npm:
        patterns:
          - "*"
