[workspace]
resolver = "2"
members = ["crates/dictymus-core", "crates/dictymus"]

[workspace.dependencies]
icu_normalizer = { version = "2", features = ["compiled_data"] }
icu_properties = { version = "2", features = ["compiled_data"] }
serde = { version = "1", features = ["derive"] }
toml = "1.1"
dirs = "6"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "parking_lot", "tracing-log"] }
tracing-appender = { version = "0.2", features = ["parking_lot"] }

[profile.release]
strip = "debuginfo"
opt-level = "s"
lto = true
panic = "abort"
codegen-units = 1

[patch.crates-io]
wxdragon = { git = "https://github.com/AllenDang/wxDragon" }
opendict-rs = { git = "https://github.com/leonardder/opendict-rs", branch = "dictymus" }
