[workspace]
resolver = "2"
members = ["crates/dictymus-core", "crates/dictymus"]

[workspace.dependencies]
icu_normalizer = { version = "2", features = ["compiled_data"] }
icu_properties = { version = "2", features = ["compiled_data"] }
serde = { version = "1", features = ["derive"] }
toml = "1.1"
dirs = "6"

[profile.release]
strip = "debuginfo"
opt-level = "s"
lto = true
panic = "abort"
codegen-units = 1

[patch.crates-io]
wxdragon = { git = "https://github.com/AllenDang/wxDragon" }
opendict-rs = { git = "https://github.com/ProjectDidymus/opendict-rs", branch = "feat/lookup-by-index" }
