[[repos]]
repo = "builtin"
hooks = [
	{ id = "trailing-whitespace" },
	{ id = "end-of-file-fixer" },
	{ id = "check-added-large-files" },
	{ id = "check-case-conflict" },
	{ id = "check-illegal-windows-names" },
	{ id = "fix-byte-order-marker" },
	{ id = "check-merge-conflict" },
	{ id = "check-toml" },
]

[[repos]]
repo = "https://github.com/rhysd/actionlint"
rev = "v1.7.12"
hooks = [
    { id = "actionlint" },
]

[[repos]]
repo = "https://github.com/doublify/pre-commit-rust"
rev = "v1.0"
hooks = [
    { id = "fmt" },
    { id = "clippy" },
]
